### PR TITLE
file: posix fallocate detection fix

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
This PR adds configure time posix_fallocate detection as well as the necessary code to fix the compilation issue in platforms where either fallocate or posix_fallocate are missing.

This is meant to fix an issue that prevented chunkio from building in freebsd.

### CODE REVIEW

**Comment by edsiper** [comment]
would you please add a unit test that forces to create a big chunk (5MB) then write 500K of data and put it down ? (that will force fallocate)

**Comment by leonardo-albertovich** [comment]
Sure, I'll get to it as soon as possible.

**Comment by edsiper** [comment]
@leonardo-albertovich it seems to me that the PR should touch this part first:

https://github.com/fluent/chunkio/blob/master/src/cio_file.c#L606-L608

**Comment by leonardo-albertovich** [comment]
What do you mean? I can't see a relation between that windows specific block and `posix_fallocate` detection.

**Comment by edsiper** [comment]
sorry I refered to the wrong lines (after the merge), these lines

https://github.com/fluent/chunkio/blob/master/src/cio_file.c#L611-L613

**Comment by edsiper** [comment]
what I see (as the previous code) it always try Linux fallocate:

https://github.com/fluent/chunkio/blob/87b096d6dbd5fda76c962efe0e330e046ea34bd3/src/cio_file_unix.c#L518

if it fails it will retry with the POSIX flavor if ENOSUPP is found. The allocation strategy is set in the chunk file context, which If I remember correctly is there because this is specific "chunkio file-backend specific information". No real issues, thinking how to move the strategy at a higher level than chunk file context

**Pull request merged**
