### PR TITLE
Fix segfault on delete unset chunk.state

### PR DESCRIPTION
**Pull request by bgaifullin**
Check that chunk state is set before delete it

### CODE REVIEW

**Comment by bgaifullin** [comment]
I agree that it is a workaround.

I do not have idea, why chunk->_state_head is in such state, like there the del was previously called and keep in this state.

there is stack trace
```
#0  0x00007f39e851e00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f39e84fd859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004a51ec in flb_signal_handler (signal=<optimized out>) at /-S/contrib/tools/fluent-bit-full/src/fluent-bit.c:581
#3  <signal handler called>
#4  __mk_list_del (prev=0x0, next=0x0) at /-S/contrib/tools/fluent-bit-full/lib/monkey/include/monkey/mk_core/mk_list.h:87
#5  mk_list_del (entry=0x7f39e4190a00) at /-S/contrib/tools/fluent-bit-full/lib/monkey/include/monkey/mk_core/mk_list.h:93
#6  chunk_state_sync (ch=0x7f39e41909c0) at /-S/contrib/tools/fluent-bit-full/lib/chunkio/src/cio_chunk.c:506
#7  cio_chunk_up_force (ch=0x7f39e41909c0) at /-S/contrib/tools/fluent-bit-full/lib/chunkio/src/cio_chunk.c:560
#8  0x0000000000c5717f in input_chunk_get (in=0x7f39e7e49000, tag=0x7f39e4387118 "tail.0", tag_len=6, chunk_size=224134, set_down=<optimized out>) at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1127
#9  input_chunk_append_raw (in=0x7f39e7e49000, n_records=359, tag=0x7f39e4387118 "tail.0", tag_len=<optimized out>, buf=0x7f39e4255e40, buf_size=224134) at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1408
#10 0x0000000000c57965 in flb_input_chunk_append_raw2 (in=0x0, records=139886675856872, tag=0x1000 <error: Cannot access memory at address 0x1000>, tag_len=0, buf=0x0, buf_size=139886675856432)
    at /home/bulatman/arc/arcadia/contrib/tools/fluent-bit-full/src/flb_input_chunk.c:1600
#11 0x000000000074e38c in process_content (file=<optimized out>, bytes=<optimized out>) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_file.c:536
#12 flb_tail_file_chunk (file=<optimized out>, file@entry=0x7f39e432fb80) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_file.c:1315
#13 0x00000000005ccba8 in in_tail_collect_event (file=file@entry=0x7f39e432fb80, config=config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail.c:310
#14 0x000000000074f760 in tail_fs_event (ins=<optimized out>, config=<optimized out>, in_context=0x7f39e6c2e000) at /-S/contrib/tools/fluent-bit-full/plugins/in_tail/tail_fs_inotify.c:267
#15 0x0000000000c551da in flb_input_collector_fd (fd=<optimized out>, fd@entry=43, config=config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/src/flb_input.c:1210
#16 0x0000000000c34599 in flb_engine_handle_event (fd=43, config=0x7f39e7e0c680, mask=<optimized out>) at /-S/contrib/tools/fluent-bit-full/src/flb_engine.c:440
#17 flb_engine_start (config=<optimized out>, config@entry=0x7f39e7e0c680) at /-S/contrib/tools/fluent-bit-full/src/flb_engine.c:763
#18 0x0000000000c5956d in flb_lib_worker (data=0x7f39e7e0b000) at /-S/contrib/tools/fluent-bit-full/src/flb_lib.c:626
#19 0x00007f39e86d5609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f39e85fa133 in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by edsiper** [comment]
@pwhelan I remember you were triaging an issue associated to this, is there any patch or outcome for the root cause ?

**Comment by pwhelan** [comment]
I am not sure that it is the same error but it has the same symptoms. After a long run where I continually create and destroy a parallel fluent-bit I pipeline I get a SIGSEGV in `cio_stream_size_chunks_up`. 

It is an extremely rare timing condition that results in a crash because the aforementioned chunk winds up being removed from the list while it is being counted. The root cause is access from another thread that is calling chunk_state_sync and removing a chunk that is being counted from the chunks list. The quick and easy solution is to merely guard all access to the chunks list via a mutex. What thread it is and why it happens so spuriously I still do not know.

This a patch that I used to bodge the issue as well as reveal that in fact there were multiple threads operating on the same chunk list:

```
diff --git a/lib/chunkio/src/cio_chunk.c b/lib/chunkio/src/cio_chunk.c
index 8916a7257..dddc0318b 100644
--- a/lib/chunkio/src/cio_chunk.c
+++ b/lib/chunkio/src/cio_chunk.c
@@ -58,7 +58,7 @@ struct cio_chunk *cio_chunk_open(struct cio_ctx *ctx, struct cio_stream *st,
 #endif
 
     /* allocate chunk context */
-    ch = malloc(sizeof(struct cio_chunk));
+    ch = calloc(1, sizeof(struct cio_chunk));
     if (!ch) {
         cio_errno();
         return NULL;
@@ -86,7 +86,9 @@ struct cio_chunk *cio_chunk_open(struct cio_ctx *ctx, struct cio_stream *st,
     }
 
     if (!backend) {
+        pthread_mutex_lock(&st->chunks_up.lock);
         mk_list_del(&ch->_head);
+        pthread_mutex_unlock(&st->chunks_up.lock);
         free(ch->name);
         free(ch);
         return NULL;
@@ -99,10 +101,14 @@ struct cio_chunk *cio_chunk_open(struct cio_ctx *ctx, struct cio_stream *st,
 
     /* Link the chunk state to the proper stream list */
     if (cio_chunk_is_up(ch) == CIO_TRUE) {
+        pthread_mutex_lock(&st->chunks_up.lock);
         mk_list_add(&ch->_state_head, &st->chunks_up);
+        pthread_mutex_unlock(&st->chunks_up.lock);
     }
     else {
+        pthread_mutex_lock(&st->chunks_up.lock);
         mk_list_add(&ch->_state_head, &st->chunks_down);
+        pthread_mutex_unlock(&st->chunks_up.lock);
     }
 
     return ch;
@@ -128,8 +134,10 @@ void cio_chunk_close(struct cio_chunk *ch, int delete)
         cio_file_close(ch, delete);
     }
 
+    pthread_mutex_lock(&ch->st->chunks_up.lock);
     mk_list_del(&ch->_head);
     mk_list_del(&ch->_state_head);
+    pthread_mutex_unlock(&ch->st->chunks_up.lock);
     free(ch->name);
     free(ch);
 
@@ -503,13 +511,21 @@ static inline void chunk_state_sync(struct cio_chunk *ch)
         return;
     }
 
-    mk_list_del(&ch->_state_head);
+    if (!mk_list_is_set(&ch->_state_head)) {
+      pthread_mutex_lock(&st->chunks_up.lock);
+      mk_list_del(&ch->_state_head);
+      pthread_mutex_unlock(&st->chunks_up.lock);
+    }
     st = ch->st;
     if (cio_chunk_is_up(ch) == CIO_TRUE) {
+        pthread_mutex_lock(&st->chunks_up.lock);
         mk_list_add(&ch->_state_head, &st->chunks_up);
+        pthread_mutex_unlock(&st->chunks_up.lock);
     }
     else {
+        pthread_mutex_lock(&st->chunks_up.lock);
         mk_list_add(&ch->_state_head, &st->chunks_down);
+        pthread_mutex_unlock(&st->chunks_up.lock);
     }
 }
 
diff --git a/lib/chunkio/src/cio_stream.c b/lib/chunkio/src/cio_stream.c
index 547d7eebf..e0489d08a 100644
--- a/lib/chunkio/src/cio_stream.c
+++ b/lib/chunkio/src/cio_stream.c
@@ -39,7 +39,7 @@ static char *get_stream_path(struct cio_ctx *ctx, struct cio_stream *st)
 
     /* Compose final path */
     len = strlen(ctx->options.root_path) + strlen(st->name) + 2;
-    p = malloc(len + 1);
+    p = calloc(1, len + 1);
     if (!p) {
         cio_errno();
         return NULL;
@@ -63,7 +63,7 @@ static int check_stream_path(struct cio_ctx *ctx, const char *path)
 
     /* Compose final path */
     len = strlen(ctx->options.root_path) + strlen(path) + 2;
-    p = malloc(len + 1);
+    p = calloc(1, len + 1);
     if (!p) {
         cio_errno();
         return -1;
@@ -116,6 +116,7 @@ struct cio_stream *cio_stream_create(struct cio_ctx *ctx, const char *name,
     int ret;
     int len;
     struct cio_stream *st;
+    pthread_mutexattr_t attr = {0};
 
     if (!name) {
         cio_log_error(ctx, "[stream create] stream name not set");
@@ -154,7 +155,7 @@ struct cio_stream *cio_stream_create(struct cio_ctx *ctx, const char *name,
         }
     }
 
-    st = malloc(sizeof(struct cio_stream));
+    st = calloc(1, sizeof(struct cio_stream));
     if (!st) {
         cio_errno();
         return NULL;
@@ -173,6 +174,9 @@ struct cio_stream *cio_stream_create(struct cio_ctx *ctx, const char *name,
     mk_list_init(&st->chunks_down);
     mk_list_add(&st->_head, &ctx->streams);
 
+    pthread_mutexattr_init(&attr);
+    pthread_mutex_init(&st->chunks_up.lock, &attr);
+
     cio_log_debug(ctx, "[cio stream] new stream registered: %s", name);
     return st;
 }
@@ -261,16 +265,18 @@ size_t cio_stream_size_chunks_up(struct cio_stream *st)
     size_t total = 0;
     struct cio_chunk *ch;
     struct mk_list *head;
+    struct timeval tv;
 
+    gettimeofday(&tv, NULL);
+    pthread_mutex_lock(&st->chunks_up.lock);
     mk_list_foreach(head, &st->chunks_up) {
         ch = mk_list_entry(head, struct cio_chunk, _state_head);
-
         bytes = cio_chunk_get_content_size(ch);
         if (bytes <= 0) {
             continue;
         }
         total += bytes;
     }
-
+    pthread_mutex_unlock(&st->chunks_up.lock);
     return total;
 }
```

I do not recommend running this patch in production or anything of the sort since I have no ideas what the ramifications are for performance or if there is the possibility of a dead lock.

**Comment by edsiper** [comment]
it seems to me this is not longer an active issue from the caller (Fluent Bit), I would prefer not to hide the corruption at this level unless we have a constant repro and this is something can happen quite often. 

Closing the PR for now.

**Pull request closed without merging**
